# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: History of Arsenal Football Club | The Invincibles | 12 FA Cup wins
email: hemdagem@gmail.com
description: A history of all the famous moments for the Arsenal Football Club. Going unbeaten in 2003/2004 which immortalised Arsenal FC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arsenalhistory.co.uk" # the base hostname & protocol for your site

plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 9
paginate_path: "/memorable-matches/page:num"


# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed

permalink: /:categories/:year/:title/

collections:
  seasons:
    output: true
    permalink: /:collection/:path/
